export const dropDownData = [
  {
    title: "Location",
    dropdown: ["All", "one", "two"],
  },
  {
    title: "Factory Id",
    dropdown: ["All", "one", "two"],
  },
  {
    title: "Material Id",
    dropdown: ["All", "one", "two"],
  },
  {
    title: "Cost",
    dropdown: ["All", "one", "two"],
  },
  {
    title: "Department",
    dropdown: ["All", "one", "two"],
  },
  {
    title: "Type of Inventory",
    dropdown: ["All", "one", "two"],
  },
];

export const tableData = {
  columns: [
    { label: "Sr. No.", align: "center" },
    { label: "SKU_Code", minWidth: 120, align: "center" },
    { label: "PRODUCT NAME/SKU ", minWidth: 120, align: "center" },
    { label: "GROUP", minWidth: 120, align: "center" },
    { label: "MATERIAL  NAME", minWidth: 120, align: "center" },
    { label: "MATERIAL COST/ Unit", minWidth: 120, align: "center" },
    { label: "MATERIAL QUANTITY", minWidth: 120, align: "center" },
    { label: "TOTAL MATERIAL COST", minWidth: 120, align: "center" },
    { label: "VENDOR ID", minWidth: 120, align: "center" },
    { label: "VENDOR NAME", minWidth: 120, align: "center" },
    { label: "HEALTH SCORE", minWidth: 120, align: "center" },
    { label: "Wasteful", minWidth: 120, align: "center" },
    { label: "Perfromance", minWidth: 120, align: "center" },
  ],
  rows: [
    [
      "1",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Steel Sheet_0.5 ft x 0.5 ft  x 10 ft ",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_001",
      "Shri Saw Mill",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "2",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Glass Sheet 4ft x 6 ft x 0.02 ft",
      " ₹ 300.00 ",
      "1",
      " ₹ 300.00 ",
      "VD_002",
      "Yash Plywoods",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "3",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Rubber Sheet 6ft x 6 ft x 0.02 ft",
      " ₹ 20.00 ",
      "6",
      " ₹ 120.00 ",
      "VD_003",
      "Jagdamba Traders",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "4",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Plastic_Sheet 4ft x 4 ft",
      " ₹ 5.00 ",
      "12",
      " ₹ 60.00 ",
      "VD_003",
      "Jagdamba Traders",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "5",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Iron Angles",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "6",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Iron Screws",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "7",
      "CAR_5S_0001",
      "Car_5 Seater",
      "Group 1",
      "Fevicol /Adhesive   50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "93",
      "Low",
      "Breakeven",
    ],
    [
      "8",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Paint 50 ml",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "9",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Iron Nut Bolts Big size",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_001",
      "Shri Saw Mill",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "10",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Steel Sheet_0.5 ft x 0.5 ft  x 10 ft ",
      " ₹ 20.00 ",
      "4",
      " ₹ 80.00 ",
      "VD_003",
      "Jagdamba Traders",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "11",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Glass Sheet 4ft x 6 ft x 0.02 ft",
      " ₹ 5.00 ",
      "8",
      " ₹ 40.00 ",
      "VD_003",
      "Jagdamba Traders",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "12",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Rubber Sheet 6ft x 6 ft x 0.02 ft",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "13",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Plastic_Sheet 4ft x 4 ft",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "14",
      "ATO_3S_001",
      "Auto_3 Seater",
      "Group 2",
      "Iron Angles",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "96",
      "Low",
      "Breakeven",
    ],
    [
      "15",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Iron Screws",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "16",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Fevicol /Adhesive   50 ml",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_001",
      "Shri Saw Mill",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "17",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Paint 50 ml",
      " ₹ 5.00 ",
      "12",
      " ₹ 60.00 ",
      "VD_003",
      "Jagdamba Traders",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "18",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Iron Nut Bolts Big size",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "19",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Steel Sheet_0.5 ft x 0.5 ft  x 10 ft ",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "20",
      "LOR_1T_002",
      "Lorry_1 Ton",
      "Group 3",
      "Glass Sheet 4ft x 6 ft x 0.02 ft",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "81",
      "High",
      "Unprofitable",
    ],
    [
      "21",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Rubber Sheet 6ft x 6 ft x 0.02 ft",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_001",
      "Shri Saw Mill",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "22",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Plastic_Sheet 4ft x 4 ft",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_002",
      "Yash Plywoods",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "23",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Iron Angles",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "24",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Iron Screws",
      " ₹ 20.00 ",
      "8",
      " ₹ 160.00 ",
      "VD_003",
      "Jagdamba Traders",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "25",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Fevicol /Adhesive   50 ml",
      " ₹ 10.00 ",
      "16",
      " ₹ 160.00 ",
      "VD_003",
      "Jagdamba Traders",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "26",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Paint 50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "27",
      "LOR_3T_001",
      "Lorry _3 Ton",
      "Group 4",
      "Steel Sheet_0.5 ft x 0.5 ft  x 10 ft ",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "95",
      "Medium",
      "Profitable",
    ],
    [
      "28",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Glass Sheet 4ft x 6 ft x 0.02 ft",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "29",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Rubber Sheet 6ft x 6 ft x 0.02 ft",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "30",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Plastic_Sheet 4ft x 4 ft",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "31",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Iron Angles",
      " ₹ 5.00 ",
      "8",
      " ₹ 40.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "32",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Iron Screws",
      " ₹ 100.00 ",
      "16",
      " ₹ 1,600.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "33",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Fevicol /Adhesive   50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "34",
      "ATO_5S_001",
      "Auto_5 Seater",
      "Group 5",
      "Paint 50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "45",
      "Medium",
      "Profitable",
    ],
    [
      "35",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Steel Sheet_0.5 ft x 0.5 ft  x 10 ft ",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "36",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Glass Sheet 4ft x 6 ft x 0.02 ft",
      " ₹ 500.00 ",
      "1",
      " ₹ 500.00 ",
      "VD_001",
      "Shri Saw Mill",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "37",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Rubber Sheet 6ft x 6 ft x 0.02 ft",
      " ₹ 5.00 ",
      "12",
      " ₹ 60.00 ",
      "VD_003",
      "Jagdamba Traders",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "38",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Plastic_Sheet 4ft x 4 ft",
      " ₹ 100.00 ",
      "1",
      " ₹ 100.00 ",
      "VD_002",
      "Yash Plywoods",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "39",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Iron Angles",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "40",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Iron Screws",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_003",
      "Jagdamba Traders",
      "75",
      "High",
      "Unprofitable",
    ],
    [
      "41",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Fevicol /Adhesive   50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_004",
      "Jagdamba Traders",
      "76",
      "High",
      "Unprofitable",
    ],
    [
      "42",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Paint 50 ml",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_005",
      "Jagdamba Traders",
      "77",
      "High",
      "Unprofitable",
    ],
    [
      "43",
      "CAR_7S_002",
      "Car_7 Seater",
      "Group 6",
      "Iron Nut Bolts Big size",
      " ₹ 50.00 ",
      "1",
      " ₹ 50.00 ",
      "VD_006",
      "Jagdamba Traders",
      "78",
      "High",
      "Unprofitable",
    ],
  ],
};
